### ISSUE TITLE
Raspberry Pi 'Internet Check' WebPage

### ISSUE THREAD

**Issue by adamboutcher** [PiSupply/iot-lora-controller#19]
It would be advantageous for you do a better network check...

`$internetCheck1 = file_get_contents('http://www.google.com');
$internetCheck2 = file_get_contents('https://status.thethings.network/');
$internetCheck3 = file_get_contents('https://www.cloudflare.com/');`

You could check for the local gateway and maybe 1.1.1.1 / 8.8.8.8 which would let you output LAN Status, WAN Status and DNS Status.

**Comment by ryanteck** [comment]
This isn't "fixed" in the sense of doing a fully different method. However I've adjusted it to instead request three different websites. HTTPBin which also is then now used to get the public IP Address. TTN Status (As a good site to check against if there's TTN issues) and instead of cloudflare.com using 1.1.1.1

To be honest I'm fairly happy and don't see much of an issue to change it much further for now. As mentioned the fact that it uses some actual webpages rather than pinging caught some issues during testing Buster releases due to an issue in compilation.
